#+title: Seguro

* Description
This is a simple application that will have a simple GUI. The purpose of this application is to speed up the process of zipping a folder encrypting it and removing the unzipped and un-encrypted version (encryption process) and also speeding up the unzipping and decrypting of the folder. The idea of the gui is to make this accessable to any person.

_Disclaimer_:
The encryption part of the project is heavily inspired by Sylvain Kerkour from her [[https://kerkour.com/rust-file-encryption-chacha20poly1305-argon2][blog]]. This resource helped me so much to understand this encryption technique and not make an insecure application. Everything is commented so if you read through the code you would understand better.

* Functionality
The app should have *two* Functionalities These should be clear to the user

    1. Encryption
    2. Decryption

** Encryption
After some research there is no easy way to zip encrypt, thus we need the long route:
    1. Zip the folder into one file (not-password protected)
    2. Ask user for a password
    3. Use argon2 for key derivation
    4. Store a hash of the key
    5. Use the key for a symmetric key cipher
    6. *DESTROY* the previous un-encrypted version

** Decryption
The encryption should be like this:

    1. Ask the user for the password of the encrypted file
    2. Use argon2 for key derivation
    3. Check the key against the hash before trying to decrypt.
    4. decryption if key is correct
    5. *DESTROY* the previous encrypted version

* Tasklist after testing
** TODO Handle the case where the vault folder is moved but the hash.txt is still there
** DONE Handle the name and how to remember it
probably a file
** DONE model the lock page
** DONE write the js to hook the rust api and frontend
** TODO Css the inputs
** TODO Css the atencion
